Repository 20je0928/C-programs, pull requests merged in 2022-10, with the labels that each got.

#3 added Euclid's Algorithm.
  GCD_Recursive.cpp
Labels: good first issue, hacktoberfest

#13 Create Product_Of_Digits.cpp
  Product_Of_Digits.cpp
Labels: good first issue, hacktoberfest, hactoberfest-accepted

#14 Create Binary_to_Decimal.cpp
  Binary_to_Decimal.cpp
Labels: hacktoberfest, hactoberfest-accepted

#15 Create Decimal_to_Binary.cpp
  Decimal_to_Binary.cpp
Labels: hacktoberfest, hactoberfest-accepted

#16 Create Kruskal.cpp
  Kruskal.cpp
Labels: hacktoberfest, hactoberfest-accepted

#11 product of numbers in digit
  binarytodecimal.c
  decimaltobinary.c
  product.c
  product.exe
Labels: hacktoberfest, hactoberfest-accepted

#17 Create Cyclesort.cpp
  Cyclesort.cpp
Labels: hacktoberfest, hactoberfest-accepted

#19 Decimal to binary using bit manipulation
  Updated_decimal_to_binary.cpp
Labels: hacktoberfest, hactoberfest-accepted

#26 Create N Queen Problem.cpp
  N Queen Problem.cpp
Labels: good first issue, hacktoberfest, hactoberfest-accepted

#27 Create Sudoku.cpp
  Sudoku.cpp
Labels: hacktoberfest, hactoberfest-accepted

#29 Create Rat in a maze.cpp
  Rat in a maze.cpp
Labels: hacktoberfest, hactoberfest-accepted

#28 Create Zig_Zag_Conversion.cpp
  Zig_Zag_Conversion.cpp
Labels: hacktoberfest, hactoberfest-accepted

#31 Create Remove Invalid Parenthesis.cpp
  Remove Invalid Parenthesis.cpp
Labels: hacktoberfest, hactoberfest-accepted

#30 Create Subset sum.cpp
  Subset sum.cpp
Labels: hacktoberfest, hactoberfest-accepted
